name: ease_my_health
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/Chizuru.jpg
    - assets/images/image.png
    - assets/images/hospital.png
    - assets/images/yashraj.png
    - assets/images/clinic.png
    - assets/images/metformin.png
    - assets/images/aspirin.png
    - assets/images/logo.png
    - assets/images/text-logo.png